title: Sridhar Sekar
logo: /assets/img/Foto.jpg
description: Exploring Data Science
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
minimal:
  skin: default
  custom_css: /assets/css/custom.css
