title: Sridhar Sekar
logo: /assets/img/Foto.jpg
badge: /assets/img/badge_0.png
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
minimal:
  skin: default
  custom_css: /assets/css/custom.css
